DROP TABLE IF EXISTS user;


CREATE TABLE user (
  id BIGINT(20) NOT NULL COMMENT '主键',
  name VARCHAR(20) NULL DEFAULT NULL ,
  age INT(11) NULL DEFAULT NULL ,
  email VARCHAR(50) NULL DEFAULT NULL ,
  PRIMARY KEY (id)
);