eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
#zuul:
  routes:
    userApi:
      path: /u/**
      serverId: user-service
    eurekaClient:
      path: /e/**
      serverId: eureka-client
spring:
  zipkin:
    base-url: http://localhost:8091/
  application:
    name: gateway-service

  sleuth:
    sampler:
      probability: 1.0
server:
  port: 8093



