server:
  port: 8092
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
spring:
  application:
    name: user-service
  zipkin:
    base-url: http://localhost:8091

  sleuth:
    sampler:
      probability: 1.0

